### PR TITLE
Replace VLA with malloc

### PR DESCRIPTION
**Pull request by jonmayergoogle**
Variable-length arrays on the stack are not portable, and only compile in gcc because of a gcc-specific extension to the language.  This patch replaces the VLA with heap-allocated memory.

### CODE REVIEW

**Comment by deece** [comment]
We won't be able to accept this as read_afu_event() is in a latency critical path.

Variable length arrays are prescribed as part of the C99 standard: http://www.open-std.org/JTC1/SC22/WG14/www/newinc9x.htm

The latest patch on master confirms that we are not using any GCC specific features (by dropping the C standard from gnu11 to c11).

Is it possible that you have removed the '-std=gnu11' switch from CFLAGS, and your compiler has defaulted to C90 mode, instead of C99 or C11? Alternatively, are you using clang++ rather than clang?

Also, if you are using a different compiler to GCC, pay attention to the error defined in libocxl_internal.h (this may not show if your compiler is masquerading as GCC). You will need to disassemble the mmio.o binary and confirm that the MMIO operations use the 32/64bit instructions mentioned in the comment.

If your toolchain is LLVM based, please be aware that it currently produces invalid machine code for the POWER9 'wait' instruction, which will be introduced in a future version of LibOCXL. When this happens, you'll need a bleeding edge LLVM, or backport the LLVM patch when it is released.

**Comment by mpe** [comment]
There's no good reason for this code to use a VLA in the first place.

All it achieves is avoids allocating space for the `ocxl_kernel_event_xsl_fault_error`, which is 32 bytes AFAICS, ie. a trivial amount of stack space.

So if latency is critical dropping the VLA and just allocating the maximum possible space is the right fix.

That also avoids the security concerns around on-stack VLAs (which are fairly moot in this case) and any compiler compatibility issues.

**Comment by deece** [comment]
@mpe Yup, a better solution would be to size the buffer using a #define based on the maximum size (currently sizeof(ocxl_kernel_event_header) + sizeof(ocxl_kernel_event_xsl_fault_error)), and leave a comment in the default block of the switch on event_api_version to update that define whenever a new case is added.

Having said that, the code has been written to C99, and I don't think it's reasonable to support compilers that don't support an almost 20 year old standard.

**Comment by mpe** [comment]
Yep, sizing based on the max size will generate better code and avoid VLAs. Win/win.

It looks like you're actually using `std=c11` and VLAs are optional in C11 apparently, so the compiler might be behaving correctly there.

**Comment by deece** [comment]
@mpe Possibly, but the handful of clang versions I tested all behaved correctly (@jonmayergoogle  has previously reported that the toolchain in use is LLVM based).

I'd really like to see from @jonmayergoogle the full output of 'make V=1' along with compiler details so we can understand the problem (and ideally, reproduce it).

**Comment by deece** [comment]
@jonmayergoogle Can you provide more information as to why this is a problem for you?

**Pull request closed without merging**
