### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by fbarrat**
A few long-standing fixes...

### CODE REVIEW

**Comment by deece** [comment]
Looks good to me

**Comment by ajdlinux** [comment]
Please add LIBOCXL_SYSPATH to the documentation

**Comment by fbarrat** [comment]
I've added a description of LIBOCXL_SYSPATH (and fixed the doxygen files to quiet warnings)

**Comment by ajdlinux** [comment]
Would be good to explicitly mention in the documentation that the default is `/sys/class/ocxl`.

I'm no Doxygen expert but the Doxygen config changes don't cause any issues on my machine, so LGTM.

I haven't tested the other changes, but they look okay to me.

**Comment by fbarrat** [comment]
I made the doc change suggested by Andrew and merged. I let it soak for at least a day to give time for people to complain and I'll tag version 1.2.0

**Pull request merged**
